# FILE: app_config/default_config.yaml
formation:
  offense_slots: 11
  defense_5_3_slots: 11
  defense_4_4_slots: 10
caps:
  interior_offense: 2
  interior_defense: 2
fairness_slider:
  - label: "Fairness-first"
    value: 0
  - label: "Balanced"
    value: 0.5
  - label: "Win-push"
    value: 1
max_consecutive: 0
