# FILE: rotation_core/explain.py
def explain_lineup(rotation):
    """
    Return a plain-language explanation of a given rotation assignment.
    """
    return "This lineup was generated by balancing player strength and fairness constraints."
