# FILE: .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Install dev dependencies
        run: |
          pip install pytest ruff black mypy
      - name: Lint with ruff
        run: ruff .
      - name: Black format check
        run: black --check .
      - name: Type check with mypy
        run: mypy .
      - name: Run tests
        run: pytest -q
